"""
api/main.py
───────────
FastAPI application entry point.

Startup sequence:
  1. Configure structured logging
  2. Register middleware (CORS, request logging)
  3. On startup: ensure Qdrant collections exist
  4. On shutdown: close Redis connection gracefully

Why lifespan over @app.on_event?
  `@app.on_event` is deprecated in FastAPI >= 0.93. The `lifespan` context
  manager is the modern, recommended pattern — it's cleaner and guaranteed
  to run shutdown logic even if an exception occurs during startup.
"""

from __future__ import annotations

import sys
from contextlib import asynccontextmanager

import structlog
import uvicorn
from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

from api.middleware import RequestLoggingMiddleware, configure_logging, setup_cors
from api.routes import router
from cache.redis_cache import close_redis
from config.settings import get_settings
from memory.qdrant_store import ensure_collections_exist

logger = structlog.get_logger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage startup and shutdown side-effects."""
    settings = get_settings()

    logger.info(
        "agentos_starting",
        env=settings.app_env,
        llm_provider=settings.llm_provider,
        llm_model=settings.llm_model,
    )

    # ── Startup ──────────────────────────────────────────────────────────────
    try:
        ensure_collections_exist()
        logger.info("qdrant_collections_ready")
    except Exception as exc:
        logger.warning(
            "qdrant_startup_failed",
            error=str(exc),
            hint="Start Qdrant with: docker compose up qdrant -d",
        )

    yield  # Application runs here

    # ── Shutdown ─────────────────────────────────────────────────────────────
    logger.info("agentos_shutting_down")
    await close_redis()
    logger.info("agentos_stopped")


# ─── Application factory ──────────────────────────────────────────────────────

def create_app() -> FastAPI:
    settings = get_settings()
    configure_logging(settings.log_level)

    app = FastAPI(
        title="AgentOS",
        description=(
            "Autonomous Multi-Agent Research System. "
            "Submit a research question and get a streamed, structured report "
            "generated by five specialist AI agents working in a LangGraph pipeline."
        ),
        version="0.1.0",
        docs_url="/docs",
        redoc_url="/redoc",
        lifespan=lifespan,
    )

    # Middleware (order matters: outermost wraps first)
    setup_cors(app)
    app.add_middleware(RequestLoggingMiddleware)

    # Routes
    app.include_router(router)

    return app


app = create_app()


# ─── CLI entry point ──────────────────────────────────────────────────────────

def main() -> None:
    settings = get_settings()
    reload = settings.app_env == "development"

    uvicorn.run(
        "api.main:app",
        host="0.0.0.0",
        port=8000,
        reload=reload,
        log_config=None,  # let structlog handle logging
        access_log=False,
    )


if __name__ == "__main__":
    main()
